from tortoise.models import Model
from tortoise import fields

class Advertiser(Model):
    advertiserID = fields.IntField(primary_key=True)
    accountManagerID = fields.CharField(255, null=True)
    advertiserName = fields.CharField(255, null=True)
    api_access = fields.CharField(255, null=True)
    status = fields.CharField(255, null=True)
    alternateID = fields.CharField(255, null=True)
    createdOn = fields.CharField(255, null=True)
    portal_access = fields.CharField(255, null=True)
    source = fields.CharField(255, null=True)
    billingCycle = fields.CharField(255, null=True)
    paymentTerm = fields.CharField(255, null=True)
    billingEmails = fields.CharField(255, null=True)
    address = fields.CharField(255, null=True)
    address2 = fields.CharField(255, null=True)
    city = fields.CharField(255, null=True)
    state = fields.CharField(255, null=True)
    zipCode = fields.CharField(255, null=True)
    country = fields.CharField(255, null=True)
    website = fields.CharField(255, null=True)
    timezone = fields.CharField(255, null=True)
    leadsDailyCap = fields.CharField(255, null=True)
    leadsWeeklyCap = fields.CharField(255, null=True)
    leadsMonthlyCap = fields.CharField(255, null=True)
    leadsDailyRevenueCap = fields.CharField(255, null=True)
    leadsWeeklyRevenueCap = fields.CharField(255, null=True)
    leadsMonthlyRevenueCap = fields.CharField(255, null=True)
    isCreditEnabled = fields.CharField(255, null=True)
    advertiserCredit = fields.CharField(255, null=True)
    allowNegativeCredit = fields.CharField(255, null=True)
    MaxNegativeCredit = fields.CharField(255, null=True)
    accountManagerName = fields.CharField(255, null=True)